### PR TITLE
tree-kill nw when cli get ctrl+c, etc

### LINKED ISSUE #10: [Feature Request] Passing argv to nw.exe
```js
// nwjs/nw
cli
  .command('*')
  .description('Run nwjs in a directory')
  .action(run)
```

https://github.com/nwjs/nw.js/wiki/App#synopsis

### PR DESCRIPTION
**Pull request by fritx**
https://github.com/segmentio/nightmare/commit/275be9e78ba7101dac6f6e09440fa2ff033eca86
- note: killing nw requires "tree-kill"
- fixme: process.onexit cant kill nw even if "end" called

fix #10

### CODE REVIEW

**Comment by fritx** [comment]
@egoist btw, I guess there is something wrong with cross-spawn-async,
as child-process-promise was working fine.
Maybe change the way to fix #10 without replacing the library?

**Comment by egoist** [comment]
Emm... I don't know what's going on for now, in fact lately I don't have much time maintaining this repo, if you can help I'd like to transfer this repo to you 😁

**Comment by fritx** [comment]
Yeah, I'd like to. If you are **really busy**, I'm happy to take this repo.
Btw, it is a cool project. Our team is using it building NW apps for company. :smile:

**Comment by egoist** [comment]
Oops, you should remove or rename `fritx/nwjs` first.

I've also added to owners of `nwjs` on NPM.

**Comment by fritx** [comment]
OK, done. It's my pleasure. Thanks!

Btw, I just found nwjs@0.13.x works fine with Ctrl+C (on Windows). It ends nw.exe immediately (but without saying "bye!").
But with nwjs@0.14.x it doesn't end nw.exe.

My PR made it kill nw.exe but it takes much more time compared to 0.13.x

**Comment by fritx** [comment]
I guess we have to review this commit https://github.com/egoist/nwjs/commit/9e1d2d29e1e7724b52fe260d26ec64b9f2043062

**Comment by egoist** [comment]
@fritx sadly I find that rename repo doesn't help 😂

OK, let's look into this issue first.

**Comment by egoist** [comment]
It's weird on my device, 0.14 works the same as 0.13 😂

**Comment by fritx** [comment]
LOL :joy: thanks, buddy.
i know this issue exist in window, but i don't have time recently. i will check it ASAP. Thanks.

**Comment by fritx** [comment]
@egoist sorry, I can't reproduce the bug on Windows now. It's wierd :astonished: 
Closing this first.

**Comment by fritx** [comment]
@egoist yup, I can reproduce the issue now.
In Windows 7 at my office.
WIth v1.3.1 it works fine, but with v1.4.0 `Ctrl+C` doesn't kill the nw process.

So I have to switch to 1.3.1 or my [fork](https://github.com/nw-cn/nwjs_/tree/kill-nw) to get on my work.

**Pull request closed without merging**
