### PR TITLE
Allow use old version node-webkit

### PR DESCRIPTION
**Pull request by iwege**
allow to download and use  old version before 0.12.

### CODE REVIEW

**Comment by fritx** [comment]
Awesome!

**Comment by egoist** [comment]
@fritx I just noticed https://github.com/nw-cn/nwjs

It seems that you guys are willing to take over this project? that would be awesome 😄

**Comment by fritx** [comment]
@egoist no... i was a mistake, lol.. It was an old old group.

**Comment by egoist** [comment]
@fritx btw I added you to this package on npm too 😄

**Comment by fritx** [comment]
@egoist n:+1: thanks! I'm gonna publish it.

**Pull request merged**
